services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: qmessenger
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  server:
    build: ./server
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgresql://user:pass@postgres/qmessenger
      REDIS_URL: redis://redis:6379
    depends_on:
      - postgres
      - redis

  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
